ALTER TABLE "TenantSettings"
ADD COLUMN IF NOT EXISTS "openHour" INTEGER,
ADD COLUMN IF NOT EXISTS "closeHour" INTEGER,
ADD COLUMN IF NOT EXISTS "availableHours" JSONB;

ALTER TABLE "Lead"
ADD COLUMN IF NOT EXISTS "source" TEXT DEFAULT 'ORGANIC';
