import {
  DINING_CART_PERMISSION_ADD_ITEM,
  DINING_CART_PERMISSION_EDIT_ITEM,
  DINING_CART_PERMISSION_REMOVE_ITEM,
  DINING_CART_PERMISSION_SUBMIT,
  DINING_CART_PERMISSION_UNLOCK_SUBMITTED_ITEM,
  DINING_CART_PERMISSION_VIEW,
} from './cart.permissions';
import {
  DINING_ORDER_ROUND_PERMISSION_CANCEL,
  DINING_ORDER_ROUND_PERMISSION_CREATE,
  DINING_ORDER_ROUND_PERMISSION_OVERRIDE,
  DINING_ORDER_ROUND_PERMISSION_SUBMIT,
  DINING_ORDER_ROUND_PERMISSION_VIEW,
} from './order-round.permissions';
import {
  DINING_SESSION_PERMISSION_ASSIGN_WAITER,
  DINING_SESSION_PERMISSION_VIEW,
  DINING_SESSION_TOKEN_PERMISSION_JOIN,
  DINING_SESSION_TOKEN_PERMISSION_LEAVE,
  DINING_SESSION_TOKEN_PERMISSION_VIEW_PARTICIPANTS,
} from './session.permissions';
import type { SessionParticipantRole } from './session.contract';

export const DINING_SESSION_PARTICIPANT_PERMISSION_REMOVE = 'dining.session-participant.remove';
export const DINING_SESSION_TRANSFER_OWNERSHIP_PERMISSION = 'dining.session.transfer-ownership';
export const DINING_ORDER_PROGRESS_VIEW_PERMISSION = 'dining.order-progress.view';

const CUSTOMER_PERMISSIONS = [
  DINING_SESSION_PERMISSION_VIEW,
  DINING_SESSION_TOKEN_PERMISSION_JOIN,
  DINING_SESSION_TOKEN_PERMISSION_LEAVE,
  DINING_CART_PERMISSION_VIEW,
  DINING_CART_PERMISSION_ADD_ITEM,
  DINING_CART_PERMISSION_EDIT_ITEM,
  DINING_CART_PERMISSION_REMOVE_ITEM,
  DINING_ORDER_ROUND_PERMISSION_CREATE,
  DINING_ORDER_ROUND_PERMISSION_SUBMIT,
  DINING_ORDER_ROUND_PERMISSION_VIEW,
];

const WAITER_PERMISSIONS = [
  ...CUSTOMER_PERMISSIONS,
  DINING_ORDER_PROGRESS_VIEW_PERMISSION,
  DINING_SESSION_TOKEN_PERMISSION_VIEW_PARTICIPANTS,
];

const MANAGER_PERMISSIONS = [
  ...WAITER_PERMISSIONS,
  DINING_ORDER_ROUND_PERMISSION_CANCEL,
  DINING_ORDER_ROUND_PERMISSION_OVERRIDE,
  DINING_CART_PERMISSION_UNLOCK_SUBMITTED_ITEM,
  DINING_SESSION_PARTICIPANT_PERMISSION_REMOVE,
  DINING_SESSION_TRANSFER_OWNERSHIP_PERMISSION,
  DINING_SESSION_PERMISSION_ASSIGN_WAITER,
];

const CASHIER_PERMISSIONS = [
  DINING_SESSION_PERMISSION_VIEW,
  DINING_CART_PERMISSION_VIEW,
  DINING_ORDER_ROUND_PERMISSION_VIEW,
  DINING_ORDER_PROGRESS_VIEW_PERMISSION,
  DINING_SESSION_TOKEN_PERMISSION_JOIN,
  DINING_SESSION_TOKEN_PERMISSION_LEAVE,
  DINING_SESSION_TOKEN_PERMISSION_VIEW_PARTICIPANTS,
];

const OBSERVER_PERMISSIONS = [
  DINING_SESSION_PERMISSION_VIEW,
  DINING_CART_PERMISSION_VIEW,
  DINING_ORDER_ROUND_PERMISSION_VIEW,
  DINING_SESSION_TOKEN_PERMISSION_VIEW_PARTICIPANTS,
];

export function resolveSessionParticipantPermissions(role: SessionParticipantRole): string[] {
  switch (role) {
    case 'WAITER':
      return [...WAITER_PERMISSIONS];
    case 'MANAGER':
      return [...MANAGER_PERMISSIONS];
    case 'CASHIER':
      return [...CASHIER_PERMISSIONS];
    case 'OBSERVER':
      return [...OBSERVER_PERMISSIONS];
    case 'CUSTOMER':
    default:
      return [...CUSTOMER_PERMISSIONS];
  }
}